apiVersion: v1
kind: PersistentVolume
metadata:
  name: videos-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: "/run/desktop/mnt/host/d/FINAL_YEAR_PROJECT/Back_End/videos" 
    type: DirectoryOrCreate

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: videos-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual




