apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffmpeg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ffmpeg
  template:
    metadata:
      labels:
        app: ffmpeg
    spec:
      containers:      
      - name: ffmpeg
        image: jrottenberg/ffmpeg:6.0-alpine
        command: ["/bin/sh", "-c", "while true; do sleep 1000; done"]

        volumeMounts:
          - name: videos-storage
            mountPath: /data

      volumes:
        - name: videos-storage
          persistentVolumeClaim:
            claimName: videos-pvc










