
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-script
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS authdb;
    CREATE DATABASE IF NOT EXISTS categorydb;
    CREATE DATABASE IF NOT EXISTS enrollmentdb;
    CREATE DATABASE IF NOT EXISTS paymentdb;
    CREATE DATABASE IF NOT EXISTS streamdb;
    CREATE DATABASE IF NOT EXISTS reviewdb;
    CREATE DATABASE IF NOT EXISTS cartdb;

---


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql   
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-script-cmap
          mountPath: /docker-entrypoint-initdb.d
        - name: mysql-p-storage
          mountPath: /var/lib/mysql
        resources:   
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: mysql-script-cmap
        configMap:
          name: mysql-script

  volumeClaimTemplates:
  - metadata:
      name: mysql-p-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: standard   
      resources:
        requests:
          storage: 2Gi   

---

apiVersion: v1
kind: Service
metadata:
  name: mysql   
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql





