# minikube mount D:\FINAL_YEAR_PROJECT:/mnt/project


apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-image-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: "/mnt/project/Back_End/Auth-service/Images" 
    type: DirectoryOrCreate

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-image-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual






