# minikube mount D:\FINAL_YEAR_PROJECT:/mnt/project

apiVersion: v1
kind: PersistentVolume
metadata:
  name: videos-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: "/mnt/project/Back_End/videos" 
    type: DirectoryOrCreate

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: videos-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual




