
server.port=8085
spring.application.name=ENROLLMENT-SERVICE

spring.datasource.url=jdbc:mysql://localhost:3306/enrollmentdb
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update

payment-service.url=${PAYMENT_URL:http://PAYMENT-SERVICE/payment}

#for kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.template.default-topic=sendMsg
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.kafka.producer.properties.schema.registry.url=${SPRING_SCHEMA_REGISTRY_URL:http://localhost:9091}


management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=ENROLLMENT-SERVICE

management.tracing.sampling.probability=1.0
spring.cloud.openfeign.micrometer.enabled=true


spring.kafka.producer.observation-enabled=true
