import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { Roboto } from "next/font/google";
import Fotter from "@/components/fotter/Fotter";
import { ToastContainer } from "react-toastify";
import { DraftContextProvider } from "../context/DraftContext";
import { PrivateContextProvider } from "@/context/helperContext";

const roboto = Roboto({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Go To",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <DraftContextProvider>
          <PrivateContextProvider>
            <Navbar />
            {children}
            <Fotter />
            <ToastContainer />
          </PrivateContextProvider>
        </DraftContextProvider>
      </body>
    </html>
  );
}
