
server.port=8084

spring.application.name=COURSE-SERVICE
spring.data.mongodb.uri=mongodb://localhost:27017/coursedb


# Maximum file size allowed for a single file upload
spring.servlet.multipart.max-file-size=1000MB

# Maximum request size allowed for multipart/form-data requests
spring.servlet.multipart.max-request-size=1000MB


auth-service.url=${AUTH_SERVICE_URL:http://API-GATEWAY/auth}

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.template.default-topic=processVideo
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.kafka.producer.properties.schema.registry.url=${SPRING_SCHEMA_REGISTRY_URL:http://localhost:9091}

management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=COURSE-SERVICE

management.tracing.sampling.probability=1.0

spring.kafka.producer.observation-enabled=true
