
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      httpclient:
        connect-timeout: 15000
        response-timeout: 35s
      globalcors:
      
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: enroll-service
          uri: http://enrollment-service-svc:8085
          predicates:
            - Path=/enroll/**
          filters:
            - AuthenticationFilter

        - id: course-service
          uri: http://course-service-svc:8084
          predicates:
            - Path=/course/**
          filters:
            - AuthenticationFilter

        - id: stream-service
          uri: http://stream-service-svc:8080
          predicates:
            - Path=/video/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: http://auth-service-svc:8081
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

        - id: category-service
          uri: http://category-service-svc:8082
          predicates:
            - Path=/category/**
          filters:
            - AuthenticationFilter

        - id: review-service
          uri: http://review-service-svc:8091
          predicates:
            - Path=/review/**
          filters:
            - AuthenticationFilter

        - id: chat-service
          uri: http://chat-service-svc:8090
          predicates:
            - Path=/room/**
          filters:
            - AuthenticationFilter


        - id: cart-service
          uri: http://cart-service-svc:8092
          predicates:
            - Path=/cart/**
          filters:
            - AuthenticationFilter


server:
  port: 9090
  address: 0.0.0.0


jwt:
  secret: ThisIsMyJwtSecretKey123456789ABCDEF

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.retry: DEBUG



