
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: basantanembang10/auth-service:36f5aa9

        ports:
        - containerPort: 8081

        volumeMounts:
          - name: image-storage
            mountPath: /app/Images           

        env:
          - name: DB_Host
            valueFrom:
              configMapKeyRef:
                key: db_host
                name: common-db-cmap

          - name: IMAGES_LOCATION
            value: /app/Images
            

      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: user-image-pvc


---

apiVersion: v1
kind: Service
metadata:
  name: auth-service-svc
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP  
    port: 8081
    targetPort: 8081

      