
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
spec:
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
      - name: course-service
        image: basantanembang10/course-service:4af70dc

        ports:
        - containerPort: 8084

        volumeMounts:
          - name: videos-storage
            mountPath: /videos     

          - name: course-image
            mountPath: /app/Images                     

        env:
          - name: MONGODB_URL
            valueFrom:
              secretKeyRef:
                key: mongodb_uri
                name: mongo-atlas-secret

          - name: AUTH_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                key: auth_service_url
                name: services-name-cmap

          - name: SPRING_BOOTSTRAP_SERVERS
            valueFrom:
              configMapKeyRef:
                key: spring_bootstrap_servers
                name: kafka-cmap

          - name: SPRING_SCHEMA_REGISTRY_URL
            valueFrom:
              configMapKeyRef:
                key: spring_schema_registry_uri
                name: kafka-cmap

          - name: IMAGES_LOCATION
            value: /app/Images

          - name: VIDEOS_LOCATION
            value: /videos/input    


      volumes:
        - name: videos-storage
          persistentVolumeClaim:
            claimName: videos-pvc     

        - name: course-image
          persistentVolumeClaim:
            claimName: course-image-pvc  

---

apiVersion: v1
kind: Service
metadata:
  name: course-service-svc
spec:
  selector:
    app: course-service
  ports:
  - protocol: TCP
    port: 8084
    targetPort: 8084

    



