
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-to
spec:
  selector:
    matchLabels:
      app: my-go-to
  template:
    metadata:
      labels:
        app: my-go-to
    spec:
      containers:
      - name: my-go-to
        image: basantanembang10/my-go-to:eac2b12

        ports:
        - containerPort: 3000

        env:
        - name: BACKEND_URL
          value: "http://api-gateway-svc:9090"  

        - name: JWT_SECRET_KEY
          value: "ThisIsMyJwtSecretKey123456789ABCDEF"

---


apiVersion: v1
kind: Service
metadata:
  name: my-go-to
spec:
  selector:
    app: my-go-to
  ports:
  - protocol: TCP  
    port: 3000
    targetPort: 3000

    