
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: basantanembang10/payment-service:aa4bbbc

        ports:
        - containerPort: 8088

        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: db_host
                name: common-db-cmap

---

apiVersion: v1
kind: Service
metadata:
  name: payment-service-svc
spec:
  selector:
    app: payment-service
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 8088



    

    


