
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-service
spec:
  selector:
    matchLabels:
      app: stream-service
  template:
    metadata:
      labels:
        app: stream-service
    spec:
      containers:
      - name: stream-service
        image: basantanembang10/stream-service:a7ae5cd

        ports:
        - containerPort: 8080

        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: db_host
                name: common-db-cmap

          - name: KAFKA_BOOTSTRAP_SERVERS
            valueFrom:
              configMapKeyRef:
                key: spring_bootstrap_servers
                name: kafka-cmap

          - name: SCHEMA_REGISTRY_URL
            valueFrom:
              configMapKeyRef:
                key: spring_schema_registry_uri
                name: kafka-cmap

          - name: OUTPUT_DIR
            value: /videos/hls    

          - name: INPUT_DIR
            value: /videos/input


        volumeMounts:
          - name: videos-storage
            mountPath: /videos

      volumes:
        - name: videos-storage
          persistentVolumeClaim:
            claimName: videos-pvc     



---

apiVersion: v1
kind: Service
metadata:
  name: stream-service-svc
spec:
  selector:
    app: stream-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080




